//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PLC", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHost")]
    public partial class PLC : object
    {
        
        private bool AsansörHareketEdebilirField;
        
        private PLCServiceReference.PLC.KapıDurumları DepoKapıDurumuField;
        
        private bool DepoyaGitField;
        
        private bool HepsiField;
        
        private bool Kat1Field;
        
        private bool Kat1_1Field;
        
        private float Kat1_1IsıField;
        
        private float Kat1_1NemField;
        
        private bool Kat1_2Field;
        
        private float Kat1_2IsıField;
        
        private float Kat1_2NemField;
        
        private bool Kat1_3Field;
        
        private float Kat1_3IsıField;
        
        private float Kat1_3NemField;
        
        private bool Kat1_4Field;
        
        private float Kat1_4IsıField;
        
        private float Kat1_4NemField;
        
        private bool Kat1_5Field;
        
        private float Kat1_5IsıField;
        
        private float Kat1_5NemField;
        
        private bool Kat1_6Field;
        
        private bool Kat2Field;
        
        private bool Kat2_1Field;
        
        private float Kat2_1IsıField;
        
        private float Kat2_1NemField;
        
        private bool Kat2_2Field;
        
        private float Kat2_2IsıField;
        
        private float Kat2_2NemField;
        
        private bool Kat2_3Field;
        
        private float Kat2_3IsıField;
        
        private float Kat2_3NemField;
        
        private bool Kat2_4Field;
        
        private float Kat2_4IsıField;
        
        private float Kat2_4NemField;
        
        private bool Kat2_5Field;
        
        private bool Kat2_6Field;
        
        private bool Kat2_7Field;
        
        private bool Kat3Field;
        
        private bool Kat3_1Field;
        
        private float Kat3_1IsıField;
        
        private float Kat3_1NemField;
        
        private bool Kat3_2Field;
        
        private bool Kat3_3Field;
        
        private bool Kat3_4Field;
        
        private bool Kat3_5Field;
        
        private bool Kat3_6Field;
        
        private PLCServiceReference.PLC.Pozisyonlar PozisyonField;
        
        private PLCServiceReference.PLC.KapıDurumları ZeminKapıDurumuField;
        
        private bool ZemineGönderField;
        
        private bool imalataGitField;
        
        private bool isConnectedField;
        
        private PLCServiceReference.PLC.KapıDurumları ÇatıKapıDurumuField;
        
        private bool ÇatıyaGönderField;
        
        private PLCServiceReference.PLC.KapıDurumları İmalatKapıDurumuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AsansörHareketEdebilir
        {
            get
            {
                return this.AsansörHareketEdebilirField;
            }
            set
            {
                this.AsansörHareketEdebilirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PLCServiceReference.PLC.KapıDurumları DepoKapıDurumu
        {
            get
            {
                return this.DepoKapıDurumuField;
            }
            set
            {
                this.DepoKapıDurumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DepoyaGit
        {
            get
            {
                return this.DepoyaGitField;
            }
            set
            {
                this.DepoyaGitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hepsi
        {
            get
            {
                return this.HepsiField;
            }
            set
            {
                this.HepsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1
        {
            get
            {
                return this.Kat1Field;
            }
            set
            {
                this.Kat1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_1
        {
            get
            {
                return this.Kat1_1Field;
            }
            set
            {
                this.Kat1_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_1Isı
        {
            get
            {
                return this.Kat1_1IsıField;
            }
            set
            {
                this.Kat1_1IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_1Nem
        {
            get
            {
                return this.Kat1_1NemField;
            }
            set
            {
                this.Kat1_1NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_2
        {
            get
            {
                return this.Kat1_2Field;
            }
            set
            {
                this.Kat1_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_2Isı
        {
            get
            {
                return this.Kat1_2IsıField;
            }
            set
            {
                this.Kat1_2IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_2Nem
        {
            get
            {
                return this.Kat1_2NemField;
            }
            set
            {
                this.Kat1_2NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_3
        {
            get
            {
                return this.Kat1_3Field;
            }
            set
            {
                this.Kat1_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_3Isı
        {
            get
            {
                return this.Kat1_3IsıField;
            }
            set
            {
                this.Kat1_3IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_3Nem
        {
            get
            {
                return this.Kat1_3NemField;
            }
            set
            {
                this.Kat1_3NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_4
        {
            get
            {
                return this.Kat1_4Field;
            }
            set
            {
                this.Kat1_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_4Isı
        {
            get
            {
                return this.Kat1_4IsıField;
            }
            set
            {
                this.Kat1_4IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_4Nem
        {
            get
            {
                return this.Kat1_4NemField;
            }
            set
            {
                this.Kat1_4NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_5
        {
            get
            {
                return this.Kat1_5Field;
            }
            set
            {
                this.Kat1_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_5Isı
        {
            get
            {
                return this.Kat1_5IsıField;
            }
            set
            {
                this.Kat1_5IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat1_5Nem
        {
            get
            {
                return this.Kat1_5NemField;
            }
            set
            {
                this.Kat1_5NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_6
        {
            get
            {
                return this.Kat1_6Field;
            }
            set
            {
                this.Kat1_6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2
        {
            get
            {
                return this.Kat2Field;
            }
            set
            {
                this.Kat2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_1
        {
            get
            {
                return this.Kat2_1Field;
            }
            set
            {
                this.Kat2_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_1Isı
        {
            get
            {
                return this.Kat2_1IsıField;
            }
            set
            {
                this.Kat2_1IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_1Nem
        {
            get
            {
                return this.Kat2_1NemField;
            }
            set
            {
                this.Kat2_1NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_2
        {
            get
            {
                return this.Kat2_2Field;
            }
            set
            {
                this.Kat2_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_2Isı
        {
            get
            {
                return this.Kat2_2IsıField;
            }
            set
            {
                this.Kat2_2IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_2Nem
        {
            get
            {
                return this.Kat2_2NemField;
            }
            set
            {
                this.Kat2_2NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_3
        {
            get
            {
                return this.Kat2_3Field;
            }
            set
            {
                this.Kat2_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_3Isı
        {
            get
            {
                return this.Kat2_3IsıField;
            }
            set
            {
                this.Kat2_3IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_3Nem
        {
            get
            {
                return this.Kat2_3NemField;
            }
            set
            {
                this.Kat2_3NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_4
        {
            get
            {
                return this.Kat2_4Field;
            }
            set
            {
                this.Kat2_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_4Isı
        {
            get
            {
                return this.Kat2_4IsıField;
            }
            set
            {
                this.Kat2_4IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat2_4Nem
        {
            get
            {
                return this.Kat2_4NemField;
            }
            set
            {
                this.Kat2_4NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_5
        {
            get
            {
                return this.Kat2_5Field;
            }
            set
            {
                this.Kat2_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_6
        {
            get
            {
                return this.Kat2_6Field;
            }
            set
            {
                this.Kat2_6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_7
        {
            get
            {
                return this.Kat2_7Field;
            }
            set
            {
                this.Kat2_7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3
        {
            get
            {
                return this.Kat3Field;
            }
            set
            {
                this.Kat3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_1
        {
            get
            {
                return this.Kat3_1Field;
            }
            set
            {
                this.Kat3_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat3_1Isı
        {
            get
            {
                return this.Kat3_1IsıField;
            }
            set
            {
                this.Kat3_1IsıField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Kat3_1Nem
        {
            get
            {
                return this.Kat3_1NemField;
            }
            set
            {
                this.Kat3_1NemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_2
        {
            get
            {
                return this.Kat3_2Field;
            }
            set
            {
                this.Kat3_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_3
        {
            get
            {
                return this.Kat3_3Field;
            }
            set
            {
                this.Kat3_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_4
        {
            get
            {
                return this.Kat3_4Field;
            }
            set
            {
                this.Kat3_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_5
        {
            get
            {
                return this.Kat3_5Field;
            }
            set
            {
                this.Kat3_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_6
        {
            get
            {
                return this.Kat3_6Field;
            }
            set
            {
                this.Kat3_6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PLCServiceReference.PLC.Pozisyonlar Pozisyon
        {
            get
            {
                return this.PozisyonField;
            }
            set
            {
                this.PozisyonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PLCServiceReference.PLC.KapıDurumları ZeminKapıDurumu
        {
            get
            {
                return this.ZeminKapıDurumuField;
            }
            set
            {
                this.ZeminKapıDurumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ZemineGönder
        {
            get
            {
                return this.ZemineGönderField;
            }
            set
            {
                this.ZemineGönderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool imalataGit
        {
            get
            {
                return this.imalataGitField;
            }
            set
            {
                this.imalataGitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isConnected
        {
            get
            {
                return this.isConnectedField;
            }
            set
            {
                this.isConnectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PLCServiceReference.PLC.KapıDurumları ÇatıKapıDurumu
        {
            get
            {
                return this.ÇatıKapıDurumuField;
            }
            set
            {
                this.ÇatıKapıDurumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ÇatıyaGönder
        {
            get
            {
                return this.ÇatıyaGönderField;
            }
            set
            {
                this.ÇatıyaGönderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PLCServiceReference.PLC.KapıDurumları İmalatKapıDurumu
        {
            get
            {
                return this.İmalatKapıDurumuField;
            }
            set
            {
                this.İmalatKapıDurumuField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PLC.KapıDurumları", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHost")]
        public enum KapıDurumları : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            boşta = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Açılıyor = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Kapanıyor = 2,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PLC.Pozisyonlar", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHost")]
        public enum Pozisyonlar : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            zemin = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            zemindepo = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            depo = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            depoimalat = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            imalat = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            imalatçatı = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            çatı = 6,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PLCServiceReference.IAsansor_Isıklar_IsıNemApi")]
    public interface IAsansor_Isıklar_IsıNemApi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLCBase/GetStatus", ReplyAction="http://tempuri.org/IPLCBase/GetStatusResponse")]
        System.Threading.Tasks.Task<PLCServiceReference.PLC> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLCBase/GetPropValue", ReplyAction="http://tempuri.org/IPLCBase/GetPropValueResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC.KapıDurumları))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC.Pozisyonlar))]
        System.Threading.Tasks.Task<object> GetPropValueAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLCBase/SetPropValue", ReplyAction="http://tempuri.org/IPLCBase/SetPropValueResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC.KapıDurumları))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PLCServiceReference.PLC.Pozisyonlar))]
        System.Threading.Tasks.Task<object> SetPropValueAsync(string name, object value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IAsansor_Isıklar_IsıNemApiChannel : PLCServiceReference.IAsansor_Isıklar_IsıNemApi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Asansor_Isıklar_IsıNemApiClient : System.ServiceModel.ClientBase<PLCServiceReference.IAsansor_Isıklar_IsıNemApi>, PLCServiceReference.IAsansor_Isıklar_IsıNemApi
    {
        
        public Asansor_Isıklar_IsıNemApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PLCServiceReference.PLC> GetStatusAsync()
        {
            return base.Channel.GetStatusAsync();
        }
        
        public System.Threading.Tasks.Task<object> GetPropValueAsync(string name)
        {
            return base.Channel.GetPropValueAsync(name);
        }
        
        public System.Threading.Tasks.Task<object> SetPropValueAsync(string name, object value)
        {
            return base.Channel.SetPropValueAsync(name, value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PLCServiceReference.IAsansor_Isıklar_IsıNem", CallbackContract=typeof(PLCServiceReference.IAsansor_Isıklar_IsıNemCallback))]
    public interface IAsansor_Isıklar_IsıNem
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsansor_Isıklar_IsıNem/isClientReg", ReplyAction="http://tempuri.org/IAsansor_Isıklar_IsıNem/isClientRegResponse")]
        System.Threading.Tasks.Task<bool> isClientRegAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IAsansor_Isıklar_IsıNemCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsansor_Isıklar_IsıNem/AsansörCycleHandler")]
        void AsansörCycleHandler(PLCServiceReference.PLC plc);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsansor_Isıklar_IsıNem/LightCycleHandler")]
        void LightCycleHandler(PLCServiceReference.PLC plc);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsansor_Isıklar_IsıNem/IsınemCycleHandler")]
        void IsınemCycleHandler(PLCServiceReference.PLC plc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IAsansor_Isıklar_IsıNemChannel : PLCServiceReference.IAsansor_Isıklar_IsıNem, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Asansor_Isıklar_IsıNemClientBase : System.ServiceModel.DuplexClientBase<PLCServiceReference.IAsansor_Isıklar_IsıNem>, PLCServiceReference.IAsansor_Isıklar_IsıNem
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Asansor_Isıklar_IsıNemClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, Asansor_Isıklar_IsıNemClientBase.GetDefaultBinding(), Asansor_Isıklar_IsıNemClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IAsansor_Isıklar_IsıNem.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Asansor_Isıklar_IsıNemClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, Asansor_Isıklar_IsıNemClientBase.GetBindingForEndpoint(endpointConfiguration), Asansor_Isıklar_IsıNemClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Asansor_Isıklar_IsıNemClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, Asansor_Isıklar_IsıNemClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Asansor_Isıklar_IsıNemClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, Asansor_Isıklar_IsıNemClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Asansor_Isıklar_IsıNemClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> isClientRegAsync()
        {
            return base.Channel.isClientRegAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IAsansor_Isıklar_IsıNem))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IAsansor_Isıklar_IsıNem))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:9002/asansorisiklarisinem");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Asansor_Isıklar_IsıNemClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IAsansor_Isıklar_IsıNem);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Asansor_Isıklar_IsıNemClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IAsansor_Isıklar_IsıNem);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IAsansor_Isıklar_IsıNem,
        }
    }
    
    public class AsansörCycleHandlerReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public AsansörCycleHandlerReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PLCServiceReference.PLC plc
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PLCServiceReference.PLC)(this.results[0]));
            }
        }
    }
    
    public class LightCycleHandlerReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public LightCycleHandlerReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PLCServiceReference.PLC plc
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PLCServiceReference.PLC)(this.results[0]));
            }
        }
    }
    
    public class IsınemCycleHandlerReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public IsınemCycleHandlerReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PLCServiceReference.PLC plc
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PLCServiceReference.PLC)(this.results[0]));
            }
        }
    }
    
    public partial class Asansor_Isıklar_IsıNemClient : Asansor_Isıklar_IsıNemClientBase
    {
        
        public Asansor_Isıklar_IsıNemClient(EndpointConfiguration endpointConfiguration) : 
                this(new Asansor_Isıklar_IsıNemClientCallback(), endpointConfiguration)
        {
        }
        
        private Asansor_Isıklar_IsıNemClient(Asansor_Isıklar_IsıNemClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public Asansor_Isıklar_IsıNemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new Asansor_Isıklar_IsıNemClientCallback(), binding, remoteAddress)
        {
        }
        
        private Asansor_Isıklar_IsıNemClient(Asansor_Isıklar_IsıNemClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public Asansor_Isıklar_IsıNemClient() : 
                this(new Asansor_Isıklar_IsıNemClientCallback())
        {
        }
        
        private Asansor_Isıklar_IsıNemClient(Asansor_Isıklar_IsıNemClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<AsansörCycleHandlerReceivedEventArgs> AsansörCycleHandlerReceived;
        
        public event System.EventHandler<LightCycleHandlerReceivedEventArgs> LightCycleHandlerReceived;
        
        public event System.EventHandler<IsınemCycleHandlerReceivedEventArgs> IsınemCycleHandlerReceived;
        
        private void OnAsansörCycleHandlerReceived(object state)
        {
            if ((this.AsansörCycleHandlerReceived != null))
            {
                object[] results = ((object[])(state));
                this.AsansörCycleHandlerReceived(this, new AsansörCycleHandlerReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnLightCycleHandlerReceived(object state)
        {
            if ((this.LightCycleHandlerReceived != null))
            {
                object[] results = ((object[])(state));
                this.LightCycleHandlerReceived(this, new LightCycleHandlerReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnIsınemCycleHandlerReceived(object state)
        {
            if ((this.IsınemCycleHandlerReceived != null))
            {
                object[] results = ((object[])(state));
                this.IsınemCycleHandlerReceived(this, new IsınemCycleHandlerReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class Asansor_Isıklar_IsıNemClientCallback : object, IAsansor_Isıklar_IsıNemCallback
        {
            
            private Asansor_Isıklar_IsıNemClient proxy;
            
            public void Initialize(Asansor_Isıklar_IsıNemClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void AsansörCycleHandler(PLCServiceReference.PLC plc)
            {
                this.proxy.OnAsansörCycleHandlerReceived(new object[] {
                            plc});
            }
            
            public void LightCycleHandler(PLCServiceReference.PLC plc)
            {
                this.proxy.OnLightCycleHandlerReceived(new object[] {
                            plc});
            }
            
            public void IsınemCycleHandler(PLCServiceReference.PLC plc)
            {
                this.proxy.OnIsınemCycleHandlerReceived(new object[] {
                            plc});
            }
        }
    }
}
