//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO.DataCollect")]
    public partial class UserDTO : object
    {
        
        private System.DateTime BasTarihiField;
        
        private int IdField;
        
        private UserServiceReference.LogDTO[] LogDTOField;
        
        private bool MainAdminField;
        
        private string addressField;
        
        private string descriptionField;
        
        private string epostaField;
        
        private string nameField;
        
        private string passwordField;
        
        private string surnameField;
        
        private string telField;
        
        private UserServiceReference.UserPermissionDTO[] userPermissionDTOField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BasTarihi
        {
            get
            {
                return this.BasTarihiField;
            }
            set
            {
                this.BasTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServiceReference.LogDTO[] LogDTO
        {
            get
            {
                return this.LogDTOField;
            }
            set
            {
                this.LogDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MainAdmin
        {
            get
            {
                return this.MainAdminField;
            }
            set
            {
                this.MainAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eposta
        {
            get
            {
                return this.epostaField;
            }
            set
            {
                this.epostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel
        {
            get
            {
                return this.telField;
            }
            set
            {
                this.telField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServiceReference.UserPermissionDTO[] userPermissionDTO
        {
            get
            {
                return this.userPermissionDTOField;
            }
            set
            {
                this.userPermissionDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO.DataCollect")]
    public partial class LogDTO : object
    {
        
        private string DurumField;
        
        private int IdField;
        
        private System.DateTime TarihField;
        
        private UserServiceReference.UserDTO UserDTOField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih
        {
            get
            {
                return this.TarihField;
            }
            set
            {
                this.TarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServiceReference.UserDTO UserDTO
        {
            get
            {
                return this.UserDTOField;
            }
            set
            {
                this.UserDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPermissionDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO.DataCollect")]
    public partial class UserPermissionDTO : object
    {
        
        private bool AlarmField;
        
        private bool AsansörField;
        
        private bool AyarlarField;
        
        private bool AydınlatmaField;
        
        private int IdField;
        
        private bool RaporlamaField;
        
        private UserServiceReference.UserDTO UserDTOField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alarm
        {
            get
            {
                return this.AlarmField;
            }
            set
            {
                this.AlarmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Asansör
        {
            get
            {
                return this.AsansörField;
            }
            set
            {
                this.AsansörField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ayarlar
        {
            get
            {
                return this.AyarlarField;
            }
            set
            {
                this.AyarlarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aydınlatma
        {
            get
            {
                return this.AydınlatmaField;
            }
            set
            {
                this.AydınlatmaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Raporlama
        {
            get
            {
                return this.RaporlamaField;
            }
            set
            {
                this.RaporlamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserServiceReference.UserDTO UserDTO
        {
            get
            {
                return this.UserDTOField;
            }
            set
            {
                this.UserDTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UserDTO/Listele", ReplyAction="http://tempuri.org/IServiceBaseOf_UserDTO/ListeleResponse")]
        System.Threading.Tasks.Task<UserServiceReference.UserDTO[]> ListeleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UserDTO/Ekle", ReplyAction="http://tempuri.org/IServiceBaseOf_UserDTO/EkleResponse")]
        System.Threading.Tasks.Task<bool> EkleAsync(UserServiceReference.UserDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UserDTO/Güncelle", ReplyAction="http://tempuri.org/IServiceBaseOf_UserDTO/GüncelleResponse")]
        System.Threading.Tasks.Task<bool> GüncelleAsync(UserServiceReference.UserDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UserDTO/Sil", ReplyAction="http://tempuri.org/IServiceBaseOf_UserDTO/SilResponse")]
        System.Threading.Tasks.Task<bool> SilAsync(UserServiceReference.UserDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IUserServiceChannel : UserServiceReference.IUserService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<UserServiceReference.IUserService>, UserServiceReference.IUserService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), UserServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UserServiceReference.UserDTO[]> ListeleAsync()
        {
            return base.Channel.ListeleAsync();
        }
        
        public System.Threading.Tasks.Task<bool> EkleAsync(UserServiceReference.UserDTO entity)
        {
            return base.Channel.EkleAsync(entity);
        }
        
        public System.Threading.Tasks.Task<bool> GüncelleAsync(UserServiceReference.UserDTO entity)
        {
            return base.Channel.GüncelleAsync(entity);
        }
        
        public System.Threading.Tasks.Task<bool> SilAsync(UserServiceReference.UserDTO entity)
        {
            return base.Channel.SilAsync(entity);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IUserService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.115:9001/User");
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IUserService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://192.168.1.115:9002/User");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserService,
            
            NetTcpBinding_IUserService,
        }
    }
}
